### ISSUE TITLE
[Semi-Bug] Inconsistent results from auto-scraper

### ISSUE THREAD

**Issue by trumpetlicks** [Asnivor/MedLaunch#101]
It seems that the auto-scraper doesn't yet do a great job of being automatic.  So many times at this point, I will multi-select some titles, try to auto-scrape them, but nothing returns for them.  If however I perform a single scrape of the title, at least one of the options (usually) comes up with much greater than a 75% statistic of it being the correct title.  Why isn't the auto-scraper simply choosing that option?

There has at this point only been a single title that didn't seem to return a high probability result, and was indeed wrong.  That happens to be "Duck Tales".  The auto-scraper actually downloaded the content for "Duck Maze".  Interestingly enough the single scrape "Pick a game" window rated that selection at 50% or less, but it still chose it, where on many games it hasn't chosen much higher probability results.

**Comment by Asnivor** [comment]
Im still working on this. Currently probability is calculated based on the number of matching words in the game title vs the titles thegamesdb.net has.

For games that only have a small number of words in their titles this can lead to a number of games with equal probability. In the case of a manual scrape this is fine as you choose the one you want. With the auto scrape though it will just skip scraping for this title when this kind of situation is encountered.

There is also a chance of it picking a wrong game if there is one clear winner during the probability test (and this game is either missing from, is named slightly differently in thegamesdb.net.

I will continue looking at this.

**Comment by Asnivor** [comment]
This should now be greatly improved as of the next release.
