### ISSUE TITLE
Download appropriate Mega Drive or Genesis covers

### ISSUE THREAD

**Issue by vkapartzianis** [Asnivor/MedLaunch#109]
Usually, there are different covers available for the "Sega Mega Drive" and "Sega Genesis" platforms. Would it be possible to download the appropriate cover, depending on the edition's country? For example, if the "country" field begins with "US" then download the Genesis cover otherwise the Mega Drive one.

![image](https://cloud.githubusercontent.com/assets/1918344/24324136/6914b74c-1189-11e7-8122-5b04f5f03051.png)

**Comment by Asnivor** [comment]
Yes, that should be possible I think.
