### ISSUE TITLE
Can't scrape info for famicom disk system games

### ISSUE THREAD

**Issue by Biofreak1987** [Asnivor/MedLaunch#110]
For example: "Yume Koujou: Doki Doki Panic", which has an entry in thegamesdb.net but MedLaunch can't seem to find it.

The file extension is .fds

**Comment by Asnivor** [comment]
This is a bug with the current scraping system. I am in the middle of moving initial scraped data from static json files to SQLite database. Once this is done it will include lookup links to FDS games (which at the moment are missing).
