### ISSUE TITLE
Scraping Data Problem

### ISSUE THREAD

**Issue by acepow3r** [Asnivor/MedLaunch#121]
Don't know when this bug first occurred, but Medlaunch 0.5.5.1 (with Mednafen 0.9.45.1-x64) is unable anymore to scrape data. It stays forever with the spinning cursor, while displaying:

**Scraping Data**
Primary Scraping (thegamesdb)
Downloading Information for: Anygame
(AnySystem)

Tried with Saturn and WonderSwan: Scrap didn't work. Tried with fresh new folders for MedLaunch 0.5.5.1 and Mednafen 0.9.45.1: Didn't work.

Tried two fresh new folders with MedLaunch 5.0 and Mednafen 0.9.43-x64 and Scrap Data worked like a charm.

**Comment by Asnivor** [comment]
@acepow3r so far I am unable to replicate this, either by manual-scraping a single game, or auto-scraping an entire system. Either way content downloads fine.

Can you actually browse to http://thegamesdb.net in a web browser?

**Comment by Asnivor** [comment]
ok, i think i can replicate it. I'll look into it

**Comment by Asnivor** [comment]
Its some kind of bug that manifests itself in a release build, but not a debug build. Further investigation needed..
