### ISSUE TITLE
Config Import message (0.5.6.0)

### ISSUE THREAD

**Issue by WizLizard** [Asnivor/MedLaunch#125]
Every time I launch MedLaunch I get this message regardless of which option I choose.

![screenshot 4](https://user-images.githubusercontent.com/12180630/27604751-424659fa-5b48-11e7-8ce3-c5a485e0e23e.png)

**Comment by Asnivor** [comment]
Interesting. I think I know what this might be. I'll take a look soon.

Thanks.
