### ISSUE TITLE
Still need some work on auto-scraping

### ISSUE THREAD

**Issue by trumpetlicks** [Asnivor/MedLaunch#152]
It does seem to work a bit better, however I just did an auto-scrape of multiple games only to find one that didn't somehow get scraped automatically.  When I went to perform a single game scrape, the "Pick a Game" window came up. Attached is a pic of what I saw.

![image](https://user-images.githubusercontent.com/5900107/28435588-9e50d812-6d61-11e7-8f86-c769d2400425.png)

As you can see, at the top, there is very EASILY a statistical match that is FAR better than any of the others.  Why is it not picking this when doing an AUTO-scrape.

**Comment by Asnivor** [comment]
@trumpetlicks I'll take a look at the local matching code again. As you have said statistically it is out on its own, so it must be a little bug somewhere that it causing it to be skipped completely when it comes to the actual scraping (rather than the initial name matching against the local ScrapeDB)

**Comment by Asnivor** [comment]
@trumpetlicks I'm struggling to replicate this issue doing an auto-scrape on multiple selected games (including the game you have drawn attention to).

I'll keep looking into it, but is there are more detail you can give? e.g., the exact steps to replicate this issue?

Many thanks.

**Comment by trumpetlicks** [comment]
The only other detail I can give is that I am doing the scrape on my favorites folder which has more than 1 system type worth of games in it.

Ryan

**Comment by Asnivor** [comment]
@trumpetlicks OK thanks. That doesnt appear to affect the outcome when I test that.
I might just re-write the scraping routine to see if that makes a difference. At the moment games are matched locally first then queued for actual scraping (and this happens last in the routine). There is a reason I did it this way originally but I don't think that applies any more (in its early days medlaunch was looking up data from static text files for local matching and it was quicker to do this in one batch).

This method has the potential for bugs to crop up, so I will maybe try processing each game 'individually' (match against local list THEN scrape immediately before moving on to the next game). If when I release the next version you still have the same issue, then I will have to look again :)

**Comment by Asnivor** [comment]
Just about to submit a fix. Hopefully this will sort the issue in the next release

**Comment by Asnivor** [comment]
Implemented in https://github.com/Asnivor/MedLaunch/releases/tag/0.5.7.2
