### ISSUE TITLE
Suggestion -Vanity names for games.

### ISSUE THREAD

**Issue by PedgeJameson** [Asnivor/MedLaunch#162]
The ability to right click a game and choose a friendly name for your favorites or even those in a list of roms.
IE: RESIDENT EVIL to Resident Evil

For those who don't like caps or even those who like to name things to "Crash 3!! My wives favorite."
Like notes but a display instead of the actual name.

**Comment by Asnivor** [comment]
This is possible. I also should probably re-do the scraping database so that all titles are first-character capitalised (This is an Example of That)

**Comment by Asnivor** [comment]
In next release - Option on the settings page to change game title formatting.

![image](https://user-images.githubusercontent.com/7911038/29276937-1cd6fc70-8108-11e7-9aa3-9c1780dfbb94.png)

**Comment by Asnivor** [comment]
Next release will have the ability to set a flag for each game: 'Manual Edit'.

Once this is set you can manually edit all the fields for each game. If manual edit remains enabled game re-scans and re-scrapes for this game will NOT update the games fields in the database.

![image](https://user-images.githubusercontent.com/7911038/30028188-fae13688-917b-11e7-8fcd-5d7f055204b4.png)

This is accessed through the 'View/Edit Game Data' option, and also enables you to:

- Manually edit the game fields
- Inspect the various matched DAT lookup entries (and copy these over to library data)
- Inspect (and re-scrape) scraping data for this game (and copy these fields over to library data)
- Inspect data obtained from the ROM itself (and copy these fields over to library data)
