### ISSUE TITLE
Sidebar issue, some game sidebars are jerking off.

### ISSUE THREAD

**Issue by PedgeJameson** [Asnivor/MedLaunch#170]
They do this, wank wank wank. I think you know what I mean.

**Comment by Asnivor** [comment]
@PedgeJameson I'm not sure that I do... Could you explain further?

**Comment by PedgeJameson** [comment]
They jump in size like there gonna hop off the page.

**Comment by Asnivor** [comment]
This might be fixed now after the manual sidebar width-change work. Will have to wait and see until this is verified.

**Comment by Asnivor** [comment]
Looks like this is fixed now. Closing until proven otherwise
