### ISSUE TITLE
Config import issue

### ISSUE THREAD

**Issue by mjuzikfrik** [Asnivor/MedLaunch#178]
Unfortunately every time I try to import config from mednafen it freezes. Be it when starting for the first time or later, it doesn't matter.

**Comment by Asnivor** [comment]
I believe this is due to the same reason as issue #179 

I am still working on it.

**Comment by Asnivor** [comment]
Can you post the Exceptions.txt file from your medlaunch directly in here please?

**Comment by mjuzikfrik** [comment]
Here you are.
[Exceptions.zip](https://github.com/Asnivor/MedLaunch/files/1285005/Exceptions.zip)
Well, it seems that you're right about the non-English issue with import and change of scheme colour. I've changed to English and it works.

Another thing. When I want to scan PSX roms/discs nothing is found. They are all in one folder bin/cue per disc.

**Comment by Asnivor** [comment]
Thanks for the exception log. This is indeed a non-english language issue. Hopefully I will get that fixed soon.

Regarding disc scanning, currently MedLaunch only supports auto-scanning of disc games where each game has its own subfolder within the designated PSX game directory.

e.g.

- PSX Games
- - A game
- - - a game.cue
- - - a game.bin
- - another game
- - - another game.ccd
- - - another game.img

I am planning to implement code to scan multiple games from the same directory, but I havent gotten around to it yet. Your workarounds are to either manually import each game by right clicking on the PSX filter in the games library (not a great solution), or moving each PSX game into its own sub-folder (again not great).

I'll let you know when I finally get the new method of disc scanning implemented.

**Comment by Asnivor** [comment]
disc scanning request moved to #180
