### ISSUE TITLE
Change screen colour freeze.

### ISSUE THREAD

**Issue by mjuzikfrik** [Asnivor/MedLaunch#179]
When I want to change the theme colour the program freezes and closes.

**Comment by Asnivor** [comment]
@mjuzikfrik Hi!

There are a number of issues at the moment with non-English language versions of Windows. I am trying to work on this and rectify them, but it is taking a while.

Would I be right in thinking your OS install is not English?

The workaround is to set your OS language as English and reboot, but obviously this is not great for everyone.

**Comment by Asnivor** [comment]
Referencing #178 & #35 

@mjuzikfrik @Crisis2032

I have compiled a dev build of MedLaunch that hopefully addresses all these issues now.

https://github.com/Asnivor/MedLaunch/raw/dev/docs/downloads/dev/MedLaunch_v0_5_12_0-DEV.zip

Would you both be able to test this to see if everything is resolved?

- Download the zip above
- Extract to a new folder (not over any existing MedLaunch directory)
- Ensure your windows language has been changed back to your native settings (Polish, French etc..)
- Run MedLaunch.exe and go through the initial setup

The things to test (to see if you can cause medlaunch to crash) are as follows:
- TopLeft Menu Bar > Visual > Change Colour Scheme
- Settings tab > medlaunch settings > change 'set gui zoom' setting
- Settings tab > medlaunch settings > change 'image tooltip size'
- Configs tab > click the orange 'import all configs from disk' button

Please let me know if you come across any more crashes, along with a description of them and a copy of the Exceptions.txt file from your MedLaunch directory (if one has been generated).

Many thanks for your help,

-Asni

**Comment by mjuzikfrik** [comment]
Confirm that everything works now. Thank you.

**Comment by Asnivor** [comment]
Great news. Thanks for the help!
