### ISSUE TITLE
Infinite Hourglass when I launch - MedLaunch_v0_5_18_1

### ISSUE THREAD

**Issue by Crisis2032** [Asnivor/MedLaunch#188]
My Configuration :
Windows 10 - 64bits - French 
Geforce GTX 970

Symptom : 
- Infinite Hourglass when I launch Medlaunch (no time to see the logo of medlauch)
(since the version MedLaunch_v0_5_12_0-DEV.zip and after... and MedLaunch_v0_5_18_1.zip)
- No log files are created (sorry...)
- When I end task Medlaunch, no possibility to delete file "MedLaunch.exe" (but I can rename the file).
I must reboot my computer and Quickly delete the file, if I'm not very quick, no possible to delete file (allready in use) even after a reboot of computer.

My Test (before every test I reboot computer) : 
- Change language, regional configurations, keyboard in United States : Same problem
- Run as Administrator : Same problem
- Run in another Hard Disk and other Directory Name : Same problem
- Try With mednafen 0.46 0.47 0.48 : same problem
- Latest Nvidia Drivers : same problem
- With MedLaunch_v0_5_8_0.zip is working

Can you send me the version between v0_5_8_0 and v0_5_12_0-DEV. 
(to see from which version there is the problem, and maybe resolve it)

**Comment by Asnivor** [comment]
There are only a couple of things that changed between versions. Please try the latest dev release - extract into a completely new folder:

https://ci.appveyor.com/project/Asnivor/medlaunch/build/ML-0.5.18.2-DEV-87/artifacts

**Comment by Crisis2032** [comment]
Same problem With this version ML-0.5.18.2-DEV-87 in a new empty folder.

**Comment by Asnivor** [comment]
ok, try dev build 88

https://ci.appveyor.com/project/Asnivor/medlaunch

it should finish building in a couple of minutes and be available on the artifacts page

**Comment by Crisis2032** [comment]
Idem, same problem

**Comment by Asnivor** [comment]
Ok, Im really not sure what is going on. I'll have to take a look at this over the next few days.

The fact that it is hanging and not even showing the splash screen is a bit weird.

**Comment by Asnivor** [comment]
you have any anti-virus that you can try disabling?

**Comment by Crisis2032** [comment]
I disable AVAST (Fuc%$*! Avast), and true, Medlauch Work !
It's Avast the problem

**Comment by Asnivor** [comment]
Excellent :)
