### ISSUE TITLE
Image Background "bug"

### ISSUE THREAD

**Issue by Crisis2032** [Asnivor/MedLaunch#189]
With the latest version MedLaunch_v0_5_18_1
Little "bug" with the background image.  
If you choose a picture, You see the picture only on the top of the interface.
the interface is not "transparency".

![medlaunchback](https://user-images.githubusercontent.com/20000514/30830110-1c0cc570-a243-11e7-8851-f8eefee60daa.jpg)

**Comment by Asnivor** [comment]
https://ci.appveyor.com/api/buildjobs/wujphgb2f210kskp/artifacts/MedLaunch%2Fbin%2FMedLaunch_v0_5_18_3-DEVBUILD-91.zip

**Comment by Crisis2032** [comment]
Thanks it's ok now !! ;)
(Hmmmm.... it's not my real background, just a test ! :p )

![medlaunchback2](https://user-images.githubusercontent.com/20000514/30832210-92028376-a24a-11e7-8d2d-30692ec7dc4b.jpg)

**Comment by Asnivor** [comment]
sure sure ;)
