### ISSUE TITLE
error with firmware gecard.pce

### ISSUE THREAD

**Issue by jjfmz42015** [Asnivor/MedLaunch#200]
error with firmware gecard.pce.

under settings when I choose firmware files all is fine except for gecard.pce

I have a good dump with proper md5.

The second I try to select set its path in medlaunch it crashes and closes.

3 other friends have the same problem.

**Comment by Asnivor** [comment]
This is now fixed in the latest dev build:
https://medlaunch.info/downloads

**Comment by jjfmz42015** [comment]
Tested. Working perfect. Thank you.


I love this front end.

**Comment by Asnivor** [comment]
No worries. I'm gonna leave this open until the next production release happens. 
Just something I do to mitigate folks opening duplicate issues between dev and production releases.

Thanks,

-Asni

**Comment by jjfmz42015** [comment]
ok thank you.

BTW:You have no idea how much I love this front end. The combo of this launcher and mednafen are ea dream!!
