### ISSUE TITLE
2.11.1 crashes when launched

### ISSUE THREAD

**Issue by retro-wertz** [Asnivor/MedLaunch#22]
2.11.1 crashes when launched, already have fresh folders for mednafen and medlaunch, windows 7

Problem signature:
  Problem Event Name:	CLR20r3
  Problem Signature 01:	MedLaunch.exe
  Problem Signature 02:	0.2.11.1
  Problem Signature 03:	582494d8
  Problem Signature 04:	mscorlib
  Problem Signature 05:	4.6.1055.0
  Problem Signature 06:	563c0eac
  Problem Signature 07:	40fd
  Problem Signature 08:	0
  Problem Signature 09:	System.Windows.Markup.XamlParse
  OS Version:	6.1.7601.2.1.0.256.1
  Locale ID:	1033
  Additional Information 1:	0a9e
  Additional Information 2:	0a9e372d3b4ad19135b953a78882e789
  Additional Information 3:	0a9e
  Additional Information 4:	0a9e372d3b4ad19135b953a78882e789

**Comment by Asnivor** [comment]
So it does.

The reason is that I stupidly forgot to include the MedLaunch.exe.config file in the release (and anyone using the in-built updater would not have seen this issue).

Thanks - I'll try and get another release out shortly

**Comment by Asnivor** [comment]
Should be now fixed in https://github.com/Asnivor/MedLaunch/releases/tag/0.2.12.2
