### ISSUE TITLE
F1 Domark bad emulation (Megadrive/Genesis)

### ISSUE THREAD

**Issue by frikiloko** [Asnivor/MedLaunch#228]
Hello,
First I want to clarify that I am talking about this game and not another: https://www.youtube.com/watch?v=9Ojq3cq0STQ

The emulation is bad when the race begins, the graphics are corrupt and with blink. This also happens with Kawasaki Superbike Challenge: https://www.youtube.com/watch?v=5Gji1xHgB4w

This error also happens in mame but there are other emulators where it works well.

Thank you very much!

**Comment by ghost** [comment]
MedLaunch is a frontend for Mednafen. all emulator-specific issues should be reported to Mednafen https://forum.fobby.net/index.php?t=thread&frm_id=3&

**Comment by frikiloko** [comment]
ok thank you
