### ISSUE TITLE
discontinued?

### ISSUE THREAD

**Issue by ghost** [Asnivor/MedLaunch#229]
Is this front end abandoned?

Not compatible to latest mednafen and silence for 8 months is why i ask?

**Comment by Asnivor** [comment]
I don't want to say abandoned just yet. I do want to update it soon. Its just finding the time at the moment, sorry.

Maybe in a few months I'll be able to bring it up to date without the AppleII stuff.

**Comment by ghost** [comment]
> I don't want to say abandoned just yet. I do want to update it soon. Its just finding the time at the moment, sorry.
> 
> Maybe in a few months I'll be able to bring it up to date without the AppleII stuff.

You responded so its alive!!! Thanks!

I only asked and worried because this front end is the definite front end for Mednafen! All the others I tried fall short.
