### ISSUE TITLE
mednafen wont launch

### ISSUE THREAD

**Issue by retro-wertz** [Asnivor/MedLaunch#23]
thanks for the fast update-but right now, mednafen wont even launch. i reverted to v0_2_11_0 so i can test it by using the update option still now working-it will just attempt to run mednafen after selecting a game then it just comes back at medlaunch just like you were closing the game. here is my current launch string:

"G:\EMULATORS\mednafen-0.9.39.2-win32.\mednafen.exe" -autosave 0 -cd.image_memcache 0 -cheats 1 -debugger.autostepmode 0 -ffnosound 0 -ffspeed 4 -fftoggle 0 -filesys.path_cheat cheats -filesys.path_firmware firmware -filesys.path_movie mcm -filesys.path_palette palettes -filesys.path_pgconfig pgconfig -filesys.path_sav sav -filesys.path_savbackup b -filesys.path_snap snaps -filesys.path_state mcs -filesys.state_comp_level 6 -filesys.untrusted_fip_check 1 -input.autofirefreq 3 -input.ckdelay 0 -input.joystick.axis_threshold 75 -input.joystick.global_focus 1 -nothrottle 0 -osd.alpha_blend 1 -osd.message_display_time 2500 -osd.state_display_time 2000 -qtrecord.h_double_threshold 256 -qtrecord.vcodec cscd -qtrecord.w_double_threshold 384 -sfspeed 0.75 -sftoggle 0 -sound 1 -sound.buffer_time 0 -sound.device default -sound.driver default -sound.period_time 0 -sound.rate 48000 -sound.volume 100 -srwframes 600 -video.blit_timesync 1 -video.deinterlacer weave -video.disable_composition 1 -video.driver opengl -video.frameskip 1 -video.fs 0 -video.glvsync 1 -lynx.lowpass 1 -lynx.rotateinput 1 -lynx.forcemono 0 -lynx.pixshader none -lynx.scanlines 0 -lynx.special none -lynx.stretch aspect_mult2 -lynx.tblur 0 -lynx.tblur.accum 0 -lynx.tblur.accum.amount 50 -lynx.videoip 0 -lynx.xres 0 -lynx.xscale 1 -lynx.xscalefs 1 -lynx.yres 0 -lynx.yscale 1 -lynx.yscalefs 1 -gb.system_type auto -gb.forcemono 0 -gb.pixshader none -gb.scanlines 0 -gb.special none -gb.stretch aspect_mult2 -gb.tblur 0 -gb.tblur.accum 0 -gb.tblur.accum.amount 50 -gb.videoip 0 -gb.xres 0 -gb.xscale 1 -gb.xscalefs 1 -gb.yres 0 -gb.yscale 1 -gb.yscalefs 1 -gba.forcemono 0 -gba.pixshader none -gba.scanlines 0 -gba.special none -gba.stretch aspect_mult2 -gba.tblur 0 -gba.tblur.accum 0 -gba.tblur.accum.amount 50 -gba.videoip 0 -gba.xres 0 -gba.xscale 1 -gba.xscalefs 1 -gba.yres 0 -gba.yscale 1 -gba.yscalefs 1 -ngp.forcemono 0 -ngp.pixshader none -ngp.scanlines 0 -ngp.special none -ngp.stretch aspect_mult2 -ngp.tblur 0 -ngp.tblur.accum 0 -ngp.tblur.accum.amount 50 -ngp.videoip 0 -ngp.xres 0 -ngp.xscale 1 -ngp.xscalefs 1 -ngp.yres 0 -ngp.yscale 1 -ngp.yscalefs 1 -nes.clipsides 0 -nes.correct_aspect 0 -nes.fnscan 1 -nes.gg 0 -nes.ggrom gg.rom -nes.input.fcexp none -nes.input.port1 gamepad -nes.input.port2 gamepad -nes.input.port3 gamepad -nes.input.port4 gamepad -nes.n106bs 0 -nes.no8lim 0 -nes.nofs 0 -nes.ntsc.brightness 0 -nes.ntsc.contrast 0 -nes.ntsc.hue 0 -nes.ntsc.matrix 0 -nes.ntsc.matrix.0 1.539 -nes.ntsc.matrix.1 -0.622 -nes.ntsc.matrix.2 -0.571 -nes.ntsc.matrix.3 -0.185 -nes.ntsc.matrix.4 0 -nes.ntsc.matrix.5 2 -nes.ntsc.mergefields 0 -nes.ntsc.preset disabled -nes.ntsc.saturation 0 -nes.ntsc.sharpness 0 -nes.ntscblitter 0 -nes.pal 0 -nes.slend 231 -nes.slendp 239 -nes.slstart 8 -nes.slstartp 0 -nes.sound_rate_error 4E-05 -nes.soundq 0 -nes.debugger.disfontsize 5x7 -nes.debugger.memcharenc cp437 -nes.pixshader none -nes.scanlines 0 -nes.special none -nes.stretch aspect_mult2 -nes.tblur 0 -nes.tblur.accum 0 -nes.tblur.accum.amount 50 -nes.videoip 0 -nes.xres 0 -nes.xscale 1 -nes.xscalefs 1 -nes.yres 0 -nes.yscale 1 -nes.yscalefs 1 -pce_fast.adpcmlp 0 -pce_fast.adpcmvolume 100 -pce_fast.arcadecard 1 -pce_fast.cdbios syscard3.pce -pce_fast.cddavolume 100 -pce_fast.cdpsgvolume 100 -pce_fast.cdspeed 1 -pce_fast.correct_aspect 1 -pce_fast.disable_softreset 0 -pce_fast.forcesgx 0 -pce_fast.input.port1 gamepad -pce_fast.input.port2 gamepad -pce_fast.input.port3 gamepad -pce_fast.input.port4 gamepad -pce_fast.input.port5 gamepad -pce_fast.mouse_sensitivity 0.5 -pce_fast.nospritelimit 0 -pce_fast.ocmultiplier 1 -pce_fast.slend 235 -pce_fast.slstart 4 -pce_fast.forcemono 0 -pce_fast.pixshader none -pce_fast.scanlines 0 -pce_fast.special none -pce_fast.stretch aspect_mult2 -pce_fast.tblur 0 -pce_fast.tblur.accum 0 -pce_fast.tblur.accum.amount 50 -pce_fast.videoip 0 -pce_fast.xres 0 -pce_fast.xscale 1 -pce_fast.xscalefs 1 -pce_fast.yres 0 -pce_fast.yscale 1 -pce_fast.yscalefs 1 -pce.adpcmextraprec 0 -pce.adpcmvolume 100 -pce.arcadecard 1 -pce.cdbios syscard3.pce -pce.cddavolume 100 -pce.cdpsgvolume 100 -pce.disable_bram_cd 0 -pce.disable_bram_hucard 0 -pce.disable_softreset 0 -pce.forcesgx 0 -pce.gecdbios gecard.pce -pce.h_overscan 0 -pce.input.multitap 1 -pce.input.port1 gamepad -pce.input.port2 gamepad -pce.input.port3 gamepad -pce.input.port4 gamepad -pce.input.port5 gamepad -pce.mouse_sensitivity 0.5 -pce.nospritelimit 0 -pce.psgrevision match -pce.resamp_quality 3 -pce.resamp_rate_error 9E-07 -pce.slend 235 -pce.slstart 4 -pce.debugger.disfontsize 5x7 -pce.debugger.memcharenc shift_jis -pce.forcemono 0 -pce.pixshader none -pce.scanlines 0 -pce.special none -pce.stretch aspect_mult2 -pce.tblur 0 -pce.tblur.accum 0 -pce.tblur.accum.amount 50 -pce.videoip 0 -pce.xres 0 -pce.xscale 1 -pce.xscalefs 1 -pce.yres 0 -pce.yscale 1 -pce.yscalefs 1 -pcfx.adpcm.emulate_buggy_codec 0 -pcfx.adpcm.suppress_channel_reset_clicks 1 -pcfx.bios pcfx.rom -pcfx.cdspeed 2 -pcfx.cpu_emulation auto -pcfx.disable_bram 0 -pcfx.disable_softreset 0 -pcfx.high_dotclock_width 1024 -pcfx.input.port1 gamepad -pcfx.input.port1.multitap 0 -pcfx.input.port2 gamepad -pcfx.input.port2.multitap 0 -pcfx.input.port3 gamepad -pcfx.input.port4 gamepad -pcfx.input.port5 gamepad -pcfx.input.port6 gamepad -pcfx.input.port7 gamepad -pcfx.input.port8 gamepad -pcfx.mouse_sensitivity 1.25 -pcfx.nospritelimit 0 -pcfx.rainbow.chromaip 0 -pcfx.resamp_quality 3 -pcfx.resamp_rate_error 9E-07 -pcfx.slend 235 -pcfx.slstart 4 -pcfx.debugger.disfontsize 5x7 -pcfx.debugger.memcharenc shift_jis -pcfx.forcemono 0 -pcfx.pixshader none -pcfx.scanlines 0 -pcfx.special none -pcfx.stretch aspect_mult2 -pcfx.tblur 0 -pcfx.tblur.accum 0 -pcfx.tblur.accum.amount 50 -pcfx.videoip 0 -pcfx.xres 0 -pcfx.xscale 1 -pcfx.xscalefs 1 -pcfx.yres 0 -pcfx.yscale 1 -pcfx.yscalefs 1 -gg.forcemono 0 -gg.pixshader none -gg.scanlines 0 -gg.special none -gg.stretch aspect_mult2 -gg.tblur 0 -gg.tblur.accum 0 -gg.tblur.accum.amount 50 -gg.videoip 0 -gg.xres 0 -gg.xscale 1 -gg.xscalefs 1 -gg.yres 0 -gg.yscale 1 -gg.yscalefs 1 -sms.fm 1 -sms.territory export -sms.forcemono 0 -sms.pixshader none -sms.scanlines 0 -sms.special none -sms.stretch aspect_mult2 -sms.tblur 0 -sms.tblur.accum 0 -sms.tblur.accum.amount 50 -sms.videoip 0 -sms.xres 0 -sms.xscale 1 -sms.xscalefs 1 -sms.yres 0 -sms.yscale 1 -sms.yscalefs 1 -md.cdbios us_scd1_9210.bin -md.correct_aspect 1 -md.input.auto 1 -md.input.mouse_sensitivity 1 -md.input.multitap none -md.input.port1 gamepad -md.input.port2 gamepad -md.input.port3 gamepad -md.input.port4 gamepad -md.input.port5 gamepad -md.input.port6 gamepad -md.input.port7 gamepad -md.input.port8 gamepad -md.region game -md.reported_region same -md.debugger.disfontsize 5x7 -md.debugger.memcharenc shift_jis -md.forcemono 0 -md.pixshader none -md.scanlines 0 -md.special none -md.stretch aspect_mult2 -md.tblur 0 -md.tblur.accum 0 -md.tblur.accum.amount 50 -md.videoip 0 -md.xres 0 -md.xscale 1 -md.xscalefs 1 -md.yres 0 -md.yscale 1 -md.yscalefs 1 -ss.bios_jp sega_101.bin -ss.bios_na_eu mpr-17933.bin -ss.bios_sanity 1 -ss.cart auto -ss.cart.kof95_path mpr-18811-mx.ic1 -ss.cart.ultraman_path mpr-19367-mx.ic1 -ss.cd_sanity 1 -ss.input.mouse_sensitivity 0.5 -ss.input.port1 gamepad -ss.input.port2 gamepad -ss.input.port3 gamepad -ss.input.port4 gamepad -ss.input.port5 gamepad -ss.input.port6 gamepad -ss.input.port7 gamepad -ss.input.port8 gamepad -ss.input.port9 gamepad -ss.input.port10 gamepad -ss.input.port11 gamepad -ss.input.port12 gamepad -ss.midsync 0 -ss.region_autodetect 1 -ss.region_default jp -ss.scsp.resamp_quality 4 -ss.slend 239 -ss.slendp 255 -ss.slstart 0 -ss.slstartp 0 -ss.smpc.autortc 1 -ss.smpc.autortc.lang english -ss.debugger.disfontsize 5x7 -ss.debugger.memcharenc SJIS -ss.forcemono 0 -ss.pixshader none -ss.scanlines 0 -ss.special none -ss.stretch aspect_mult2 -ss.tblur 0 -ss.tblur.accum 0 -ss.tblur.accum.amount 50 -ss.videoip 0 -ss.xres 0 -ss.xscale 1 -ss.xscalefs 1 -ss.yres 0 -ss.yscale 1 -ss.yscalefs 1 -psx.bios_eu scph5502.bin -psx.bios_jp scph5500.bin -psx.bios_na scph5501.bin -psx.bios_sanity 1 -psx.cd_sanity 1 -psx.dbg_level 0 -psx.h_overscan 1 -psx.input.analog_mode_ct 0 -psx.input.mouse_sensitivity 1 -psx.input.port1 gamepad -psx.input.port1.analogjoy.axis_scale 1 -psx.input.port1.dualanalog.axis_scale 1 -psx.input.port1.dualshock.axis_scale 1 -psx.input.port1.gun_chairs 0xFF0000 -psx.input.port1.memcard 1 -psx.input.port2 gamepad -psx.input.port2.analogjoy.axis_scale 1 -psx.input.port2.dualanalog.axis_scale 1 -psx.input.port2.dualshock.axis_scale 1 -psx.input.port2.gun_chairs 0xFF0000 -psx.input.port2.memcard 1 -psx.input.port3 gamepad -psx.input.port3.analogjoy.axis_scale 1 -psx.input.port3.dualanalog.axis_scale 1 -psx.input.port3.dualshock.axis_scale 1 -psx.input.port3.gun_chairs 0xFF0000 -psx.input.port3.memcard 1 -psx.input.port4 gamepad -psx.input.port4.analogjoy.axis_scale 1 -psx.input.port4.dualanalog.axis_scale 1 -psx.input.port4.dualshock.axis_scale 1 -psx.input.port4.gun_chairs 0xFF0000 -psx.input.port4.memcard 1 -psx.input.port5 gamepad -psx.input.port5.analogjoy.axis_scale 1 -psx.input.port5.dualanalog.axis_scale 1 -psx.input.port5.dualshock.axis_scale 1 -psx.input.port5.gun_chairs 0xFF0000 -psx.input.port5.memcard 1 -psx.input.port6 gamepad -psx.input.port6.analogjoy.axis_scale 1 -psx.input.port6.dualanalog.axis_scale 1 -psx.input.port6.dualshock.axis_scale 1 -psx.input.port6.gun_chairs 0xFF0000 -psx.input.port6.memcard 1 -psx.input.port7 gamepad -psx.input.port7.analogjoy.axis_scale 1 -psx.input.port7.dualanalog.axis_scale 1 -psx.input.port7.dualshock.axis_scale 1 -psx.input.port7.gun_chairs 0xFF0000 -psx.input.port7.memcard 1 -psx.input.port8 gamepad -psx.input.port8.analogjoy.axis_scale 1 -psx.input.port8.dualanalog.axis_scale 1 -psx.input.port8.dualshock.axis_scale 1 -psx.input.port8.gun_chairs 0xFF0000 -psx.input.port8.memcard 1 -psx.input.pport1.multitap 0 -psx.input.pport2.multitap 0 -psx.region_autodetect 1 -psx.region_default jp -psx.slend 239 -psx.slendp 287 -psx.slstart 0 -psx.slstartp 0 -psx.spu.resamp_quality 5 -psx.debugger.disfontsize 5x7 -psx.debugger.memcharenc shift_jis -psx.forcemono 0 -psx.pixshader none -psx.scanlines 0 -psx.special none -psx.stretch aspect_mult2 -psx.tblur 0 -psx.tblur.accum 0 -psx.tblur.accum.amount 50 -psx.videoip 0 -psx.xres 0 -psx.xscale 1 -psx.xscalefs 1 -psx.yres 0 -psx.yscale 1 -psx.yscalefs 1 -snes_faust.input.port1 gamepad -snes_faust.input.port2 gamepad -snes_faust.resamp_quality 3 -snes_faust.resamp_rate_error 3.5E-05 -snes_faust.spex 0 -snes_faust.spex.sound 1 -snes_faust.forcemono 0 -snes_faust.pixshader none -snes_faust.scanlines 0 -snes_faust.special none -snes_faust.stretch aspect_mult2 -snes_faust.tblur 0 -snes_faust.tblur.accum 0 -snes_faust.tblur.accum.amount 50 -snes_faust.videoip 0 -snes_faust.xres 0 -snes_faust.xscale 1 -snes_faust.xscalefs 1 -snes_faust.yres 0 -snes_faust.yscale 1 -snes_faust.yscalefs 1 -snes.apu.resamp_quality 5 -snes.correct_aspect 0 -snes.input.port1 gamepad -snes.input.port1.multitap 0 -snes.input.port2 gamepad -snes.input.port2.multitap 0 -snes.mouse_sensitivity 2 -snes.forcemono 0 -snes.pixshader none -snes.scanlines 0 -snes.special none -snes.stretch aspect_mult2 -snes.tblur 0 -snes.tblur.accum 0 -snes.tblur.accum.amount 50 -snes.videoip 0 -snes.xres 0 -snes.xscale 1 -snes.xscalefs 1 -snes.yres 0 -snes.yscale 1 -snes.yscalefs 1 -vb.3dmode anaglyph -vb.3dreverse 0 -vb.allow_draw_skip 0 -vb.anaglyph.lcolor 0xffba00 -vb.anaglyph.preset red_blue -vb.anaglyph.rcolor 0x00baff -vb.cpu_emulation fast -vb.default_color 0xF0F0F0 -vb.disable_parallax 0 -vb.input.instant_read_hack 1 -vb.instant_display_hack 0 -vb.liprescale 2 -vb.sidebyside.separation 0 -vb.debugger.disfontsize 5x7 -vb.debugger.memcharenc shift_jis -vb.forcemono 0 -vb.pixshader none -vb.scanlines 0 -vb.special none -vb.stretch aspect_mult2 -vb.tblur 0 -vb.tblur.accum 0 -vb.tblur.accum.amount 50 -vb.videoip 0 -vb.xres 0 -vb.xscale 1 -vb.xscalefs 1 -vb.yres 0 -vb.yscale 1 -vb.yscalefs 1 -wswan.bday 23 -wswan.blood o -wswan.bmonth 6 -wswan.byear 1989 -wswan.language english -wswan.name Mednafen -wswan.rotateinput 0 -wswan.sex female -wswan.forcemono 0 -wswan.pixshader none -wswan.scanlines 0 -wswan.special none -wswan.stretch aspect_mult2 -wswan.tblur 0 -wswan.tblur.accum 0 -wswan.tblur.accum.amount 50 -wswan.videoip 0 -wswan.xres 0 -wswan.xscale 1 -wswan.xscalefs 1 -wswan.yres 0 -wswan.yscale 1 -wswan.yscalefs 1 -wswan.debugger.disfontsize 5x7 -wswan.debugger.memcharenc shift_jis "G:\EMULATORS\ConsoleRoms\Famicom-NoIntro.\akumajou dracula (japan).zip"

**Comment by Asnivor** [comment]
Looks like I have some work to do (although I doubt i will have time this weekend). definitely looks like a problem with the new way config commands are handled.

For now, please extract 0.2.11.0 ( https://github.com/Asnivor/MedLaunch/releases/tag/0.2.11.0 ) to a new folder then extract 0.2.11.1 over the top of it ( https://github.com/Asnivor/MedLaunch/releases/tag/0.2.11.1).

This should get you up and running (although don't use the in-app updater until a new release is out).

Thanks.

**Comment by Asnivor** [comment]
0.2.11.1 release has now been fixed (so you shoudlnt have to download 11.0 first.

This has none of the new breaking code. If you game still doesnt launch please post the launch string again along with the contents of the mednafen-09x.cfg file in your mednafen directory.

Thanks.

**Comment by Asnivor** [comment]
> "G:\EMULATORS\ConsoleRoms\Famicom-NoIntro.\akumajou dracula (japan).zip"

retro-wertz: are you still seeing the same problem with this game using MedLaunch 0.2.11.1?
If so, can you check the output in the stout.txt file in the Mednafen directory immediately after trying to launch the game?

This is a Famicon disk system game that requires 'disksys.rom' present in the root of the Mednafen directory. Could this be the problem?

**Comment by retro-wertz** [comment]
hi, i did not test the new uploaded 0.2.11.1, since i managed to get the old one working by installing 0.2.11.0 then overwrite that with the old 0.2.11.1.

i am using the cartridge version of akumajou dracula so i do not believe its an fds rom issue. other games behaves the same.

do you have any plans to use per-system config? like if its a nes game it will have separate nes related config named nes.cfg?

**Comment by Asnivor** [comment]
> hi, i did not test the new uploaded 0.2.11.1, since i managed to get the old one working by installing 0.2.11.0 then overwrite that with the old 0.2.11.1.
> i am using the cartridge version of akumajou dracula so i do not believe its an fds rom issue. other games behaves the same.

Weird, I cant seem to replicate the issue you are having (unless I remove disksys.rom from my mednafen directory). Hopefully the next release should throw a bit more light on the problem.

> do you have any plans to use per-system config? like if its a nes game it will have separate nes related config named nes.cfg?

Thats kind of how it works at the moment if you enable the 'NES' configuration on the configs tab (although it doesnt ever save anything to nes.cfg, it just has seperate configuration entries in the MedLaunch database). The application logic is really convoluted though at the moment.

The next release I think I am going to get rid of 'Base Configuration' entirely and just have seperate config filters for each system. This will make it easier when populating the launcher settings from actual Mednafen config files (and also when exporting to system specific config files if this gets implemented). 

Eventually I want to have an option to work directly off on-disk config files (not MedLaunch's internal database), but this is some way out.

I also hope to have a dialog popup after game launch if any errors are detected in the Mednafen log - this should make troublshooting much easier.

Bear with me, hopefully a new release will be finished soon :)

**Comment by retro-wertz** [comment]
hmm, wierd. it does seem to work now.. although although new version still passes unnecessary other system-related-config in command launch string... let me do some tests, i get back to you when i can replicate what happened....

**Comment by Asnivor** [comment]
No problem. I'm in the middle of overhauling the launch string stuff so that it only passes what is necessary.

When the next release is nearly done I might post a link to a dev build for you if you are interested in testing before I release proper?

Thanks.

**Comment by retro-wertz** [comment]
OK found what caused that issue. this happens if you are using 32-bit version of mednafen 0.9.39.2. the error is caused by passing the "-ss.bios_jp" command-line, but it does not affect the 64bit mednafen

> Starting Mednafen 0.9.39.2
>  Build information:
>    Compiled with gcc 4.9.2
>    Running with MinGW-W64 Runtime 3.3 (stable - rev. 6583) 2014-04-15
>    Compiled against zlib 1.2.8, running with zlib 1.2.8(flags=0x00000055)
>    Compiled against libiconv 14.1, running with libiconv 14.1
>    Compiled against SDL 1.2.15, running with SDL 1.2.15
>    Running with libsndfile-1.0.27
>  Base directory: G:\EMULATORS\TEST\mednafen.
>  Emulation modules: nes snes gb gba pce lynx md pcfx ngp psx ssfplay vb wswan sms gg snes_faust pce_fast demo cdplay
>  Loading settings from "G:\EMULATORS\TEST\mednafen.\mednafen-09x.cfg"...
>   Loaded 3065 valid settings and 0 unknown settings.
> Unrecognized argument: -ss.bios_jp
>

**Comment by Asnivor** [comment]
Many thanks for this.

Thats very odd indeed. Perhaps 32-bit windows can only accept a certain number of characters on the command line? If this is the case it should be fixed in the next release (when only needed commands are passed on the command line).

If not, I will look into it further.

**Comment by Asnivor** [comment]
> also, there seem to be something wrong in how medlaunch passes the "path" to mednafen, look at that quoute above, there is a . after my mednafen path ---->> Loading settings from "G:\EMULATORS\TEST\mednafen.\mednafen-09x.cfg"...", and this gets passed to mednafen's other folders as well (like \mednafen.\cheats, \mednafen.\firmware etc)

Thats nothing to worry about and will not break anything (windows handles this as a sub-directory).

Thanks

**Comment by retro-wertz** [comment]
probably just a compile error with the 32bit version of mednafen, although a more simplier launch string would still be better or probably make use of cfg instead.

**Comment by Asnivor** [comment]
> probably just a compile error with the 32bit version of mednafen, although a more simplier launch string would still be better or probably make use of cfg instead.

Ahhh! That is it. The Saturn emulation is only implemented in the 64-bit version of Mednafen.

Many thanks.

**Comment by retro-wertz** [comment]
ok no wonder i cant seem to get my segasaturn images to run, i kept running it under 32-bit mednafen >.<

**Comment by Asnivor** [comment]
Unnecessary command line options removed in master branch : https://github.com/Asnivor/MedLaunch/commit/cae468c1199865d908e8b1114de2fbbf2276a09c
