### ISSUE TITLE
pce_fast config missing from latest release build

### ISSUE THREAD

**Issue by retro-wertz** [Asnivor/MedLaunch#24]
this is just a quick test-pce fast has missing pce_fast related entries in cfg, medlaunch has no effect on it too, command line does not have -pce. related config. normal pce works, and so has nes and snes. im not sure if there are missing individual config though.

performance related - loading medlaunch seems took quite a bit of time before seeing the main menu, is it rescanning rom folders or something?

**Comment by Asnivor** [comment]
> this is just a quick test-pce fast has missing pce_fast related entries in cfg, medlaunch has no effect on it too, command line does not have -pce. related config. normal pce works, and so has nes and snes. im not sure if there are missing individual config though.

Thanks again, I'll look at this today. There are definitely a few bugs that have slipped in with the configs.

> performance related - loading medlaunch seems took quite a bit of time before seeing the main menu, is it rescanning rom folders or something?

No, but it does do quite a bit internal processing/checking when starting as the UI is quite complex.

Does this happen every time you run MedLaunch, or just on first-run (where database needs to be generated or updated).

**Comment by Asnivor** [comment]
Ok, I believe the config issues to be resolved now.

The 'loading medlaunch' speed issues may be sorted now that the configs controls are being populated properly. oBviously the first time you run MedLaunch after either a fresh install or upgrade of existing install can take some time.

Fixes are currently in the master branch https://github.com/Asnivor/MedLaunch/commit/4410952e66099bc17acba38f4eb9df5cf90ee8f5

I'll try and get a release out today and leave this issue open until you can report whether (or not) the problems are now fixed.

Thanks

**Comment by retro-wertz** [comment]
pce config issue fixed now, using pce_fast mostly here with supergrafx mode.

**Comment by Asnivor** [comment]
Awesome :)

Thanks for the help.

**Comment by Asnivor** [comment]
Resolved in release: https://github.com/Asnivor/MedLaunch/releases/tag/0.2.14.5
