### ISSUE TITLE
(not priority)batch scraping data, unchecked media still being scanned and downloaded

### ISSUE THREAD

**Issue by retro-wertz** [Asnivor/MedLaunch#25]
scrap function downloads everything even if some media was unchecked checked on settings, just wanted rom/game info and not extra media files but those are still being scanned for and downloaded

also add columns for game data like year,genre, developer or publisher if available.

**Comment by Asnivor** [comment]
> scrap function downloads everything even if some media was unchecked checked on settings, just wanted rom/game info and not extra media files but those are still being scanned for and downloaded

I'll look into that.

> also add columns for game data like year,genre, developer or publisher if available.

Those fields are there in the sidebar and should only be shown if that specific data has been scraped (and is available on the site that you have scraped from):

![image](https://cloud.githubusercontent.com/assets/7911038/20357916/bf60909e-ac21-11e6-8f8e-b5bd3f0ff16a.png)

Are you saying that you want these columns to also appear in the main games library list?

Thanks.

**Comment by retro-wertz** [comment]
i wanted them also in columns so i can sort games by like all irem games or konami releases.

**Comment by Asnivor** [comment]
Ok cool. That is do-able with a bit or work. Currently once a game is scraped a .json file is generated in the data folder for that game.

If I were to pull in data from all these files as the datagrid is 'built' it would be fantastically slow. Its probably more sensible to have a few more fields in the Game database that get populated every time a game is scraped (and wiped out if the scraping link between game data and game database entry is removed).

Its definitely a good idea though (maybe with settings to show or hide these columns for users that dont want to see them). I'll create an 'enhancement' issue on GitHub for this and get to it when i get to it :)

Thanks.

**Comment by Asnivor** [comment]
Media downloading bug fixed in commit https://github.com/Asnivor/MedLaunch/commit/eaa800adcd2e42110c2770eb0fba2b446db2adcc

Enhancement request moved to new issue
