### ISSUE TITLE
tg16/pce cd launchstring and cfg and enhancements suggestions?

### ISSUE THREAD

**Issue by retro-wertz** [Asnivor/MedLaunch#27]
-tg16/pce cd games the pce/pce_fast launch strings are not being passed to them, medlaunch config does not affect them too. 
-an extra pcecd.cfg config being created in mednafen folder which i dont think mednafen even uses.
-(enhancement) unscrapped games list needs separate db for faster access? 
-(enhancement) a more friendly name for game data like actual game name and not numbers?
-identify and scrap game - some games i have, like Cotton - Fantastic Night Dreams exist in you gamedb but does not appear in selection - feature unfinished or need mode db data?

**Comment by Asnivor** [comment]
> -tg16/pce cd games the pce/pce_fast launch strings are not being passed to them, medlaunch config does not affect them too.

Ahh, yes I will fix this

> -an extra pcecd.cfg config being created in mednafen folder which i dont think mednafen even uses.

You are right, it does not - i'll fix this.

> -(enhancement) unscrapped games list needs separate db for faster access?

Yeah, you are right. At the moment it is basically pulling a list of games from the database that don't have a game data json file present. This means it is quite disk-read-heavy and ultimately pretty slow. I'll have a think about solutions for this

> -(enhancement) a more friendly name for game data like actual game name and not numbers?

This might be a problem. The gameid that is specified in the game data folder is actually the internal ID that thegamesdb.net uses for their games. There is a link database table that matches up internal MedLaunch gameIds with thegamesdb.net ids when a game is scraped. Renaming these folders can be done, but it does add quite a bit of complexity to the code. We would also run into issues if the game name happens to change for a particular ID on thegamesdb.net. I'll think about this further.

> -identify and scrap game - some games i have, like Cotton - Fantastic Night Dreams exist in you gamedb but does not appear in selection - feature unfinished or need mode db data?

I see what is causing this and will address this soon. It is a bug where the scraper is actually looking for TuboGrafx games when you try to scrape a TuboGrafx-CD game (and obviously it doesnt find any matches).


I just also want to say that I am extremely grateful for all the troubleshooting/suggestions that you have been doing recently. To me this is what open-source is all about and I seriously doubt I would have found half of these bugs so quickly without you.

Thanks again.

**Comment by Asnivor** [comment]
Enhancement requests moved to seperate issues.
All bugs fixed in master branch (and will be available in next release)

**Comment by retro-wertz** [comment]
tg16/pce-cd batch scrapping do not work-individual scrapping does

media scanning options seems to work now.

**Comment by Asnivor** [comment]
Will be available in next release
