### ISSUE TITLE
Crash when changing UI zoom factor

### ISSUE THREAD

**Issue by Asnivor** [Asnivor/MedLaunch#35]
So far unable to replicate this (although it has been reported by 2 separate people).

Need to implement some exception logging to try and track down the cause.

**Comment by Asnivor** [comment]
Really need to see an 'Exceptions.log' file from the MedLaunch directory of someone who is experiencing this problem. 

I have so far been unable to replicate this bug myself.

**Comment by PedgeJameson** [comment]
Explain I can see if I can replicate.

**Comment by Asnivor** [comment]
@PedgeJameson there was only one person reported it MANY versions ago. I'm tempted to close it off as noone else has flagged the same problem.

Apparently, there was a crash when you go to Settings and change the UI zoom factor.

**Comment by Crisis2032** [comment]
I have the same problem. And Medlaunch Crash too when a try to Change Color Sheme.
Maybe it's because I use a 4K monitor (and 3840x2160 resolution).


[Exceptions set GUI Zoom.txt](https://github.com/Asnivor/MedLaunch/files/1257427/Exceptions.set.GUI.Zoom.txt)
[Exceptions change Visual Sheme.txt](https://github.com/Asnivor/MedLaunch/files/1257428/Exceptions.change.Visual.Sheme.txt)

**Comment by PedgeJameson** [comment]
Let me try a couple times on different circumstances and I'll let you guys
know in a few minute

**Comment by PedgeJameson** [comment]
It doesn't crash, it just used to zooooooooooom back and forth. OK, now you're saying it crashing when you change the theme?

**Comment by Crisis2032** [comment]
I just click on visual, on Change Color Theme, and it crash immediatly

**Comment by PedgeJameson** [comment]
That's strange. Whats your resolution and video card again?

**Comment by PedgeJameson** [comment]
Being an interface, it is a pain in the ass. But as a GUI. Most are. Lower your res and try again.

**Comment by Crisis2032** [comment]
same problem in 1920x1080

**Comment by PedgeJameson** [comment]
Video card?

**Comment by Crisis2032** [comment]
NVIDIA Geforce GTX970

**Comment by PedgeJameson** [comment]
Ok, update your drivers, I know everyone says that, but it does make a difference. NVIDIA does dick around ALOT. Let me know after.

**Comment by Crisis2032** [comment]
same problem after update and reboot

**Comment by PedgeJameson** [comment]
.....thinking

**Comment by PedgeJameson** [comment]
youd prolly have to wait for the dev. if I can't figure it out then hes the one. dont change the color then. you can do it manually.

**Comment by Asnivor** [comment]
@Crisis2032 @PedgeJameson Hi guys, sorry I have been away on holiday for a week.

@Crisis2032 I notice that you are using a French OS.

The exception is being generated when a double value (a number with decimal characters) is parsed as a string from a textbox.

It is possible that some non-English language setups use a comma (,) to denote a decimal point rather than a full-stop/period (.). Are you able to confirm that this is the case (maybe in another application like Excel for example)?

If so, i'll try to add some culture-agnostic code and post a quick dev build for you to try before the next full release. Hopefully that should put this issue to bed once and for all.

**Comment by Asnivor** [comment]
@Crisis2032 Can you test with the dev build below to see if the issue is now resolved?

https://medlaunch.info/temp/MedLaunch_v0_5_11_0-DEV.zip

I am aiming to release tomorrow morning (or sooner if I hear back from you before then).

Many thanks,

-Asni

PS: @PedgeJameson feel free to try the dev release also ;)

**Comment by PedgeJameson** [comment]
Anything else new in it btw?

**Comment by Asnivor** [comment]
@PedgeJameson 

So far:

* (BugFix)	-	New version downloads don't stall at 100% anymore (but obviously you will still have to manually update until you are running this version)
* (Enhancement)	-	Added setting to reformat game title case when displayed in the library. Options - no change, Title (Camel) Case, All Caps
* (Enhancement)	-	Context menu option to delete ROM(s) from disk - currently only ROM games that are either uncompressed, or are the only ROM file within a zip file (disc-based games and 7zipped ROMs not supported)
* (UI)	-	Re-styled the games library favourite 'tick box' so that it no longer looks terrible
* (Enhancement)	- Added the following controller configuration options: Saturn (light gun & mouse), SNES (superscope & mouse), PSX (guncon, justifier & mouse), PCE/PCE_FAST (mouse), PCFX (mouse), NES (zapper) and MD (mouse)
* (UI)	-	Controller configuration now shows 'pretty' names for Keyboard & Mouse bindings (hovering over each binding does however show the actual mednafen command in a tooltip)
* (BugFix)	-	Binding of tertiary controller settings is now possible
* (Enhancement) - Compatibility and download links for mednafen 0.9.47
* (Enhancement) - Added basic ROM/Disc inspector functionality
* (BugFix)	-	Library game info text now auto-scrolls if right boundary is breached

**Comment by Crisis2032** [comment]
I test in 5 minutes  :)

**Comment by Crisis2032** [comment]
This dev version doesnt work on my computer (not possible to launch... I wait... wait... and wait...)

But, I confirm in France they use , and . for decimal (the both, some progrms . others , )

**Comment by Crisis2032** [comment]
If I set my Windows in United-States default laguage, and I reboot my computer.
I have Windows in English, and no problem when I changing UI zoom factor, or Change color Theme.

**Comment by Asnivor** [comment]
@Crisis2032 ok thanks. I guess I have a little more work to do :)

**Comment by Asnivor** [comment]
@Crisis2032 to confirm, if you extract the dev version into its own new folder and launch it, medlaunch does not start?

**Comment by Crisis2032** [comment]
Yes I try this too and I confirm. Medlaunch Dev version does not start if I extract in a new folder and launch it.

**Comment by Asnivor** [comment]
Well, ive installed the french version of Win7 to test and the dev version does start. However it wont let me choose a mednafen directory.

It looks like there could be a large number of localisation/culture issues that I will have to work on over time. This will not be a quick fix unfortunately.

**Comment by Crisis2032** [comment]
If you need some other test, just ask. :)
Thanks for all ! ;)

**Comment by Asnivor** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Culture-Specific exceptions](https://trello.com/c/DmpIDxHD/2-culture-specific-exceptions)

**Comment by Crisis2032** [comment]
You want I try your new dev version ?

**Comment by Asnivor** [comment]
@Crisis2032 sure. 

From now on the latest dev version (if one is available) is at the bottom of the downloads page:

https://medlaunch.info/downloads

Thanks.

**Comment by Crisis2032** [comment]
No possible to launch the latest version : 0.5.12.0
I launch in a empty directory : eternal hourglass

**Comment by Asnivor** [comment]
I cannot replicate this at all (and it is working fine for other users).

Can you right-click on the medlaunch.exe and 'run as administrator'?

**Comment by Crisis2032** [comment]
Same problem after reboot
and executed as Administrator. No problem with the old official version

**Comment by Crisis2032** [comment]
Ahhh and now not possible to open old version !! X_x !
Maybe I must remove some Visual C++ installation or some entries with regedit ???

**Comment by Asnivor** [comment]
I dont think that will help.

Make sure your operating system is fully up to date with windows updates.

When the application hangs at start how far does it get? Does it show the splash screen? does it show the initialization console?

Is there an Exceptions.txt file generated in the medlaunch directory?

**Comment by Crisis2032** [comment]
Good news !!! :)

Initial problem : eternal hourglass

I use Ccleaner to erase all temp files...
- New problem : watch logo Medlaunch and crash after

I delete all my medlaunch database and configuration
- No problem !!!!

The problem come from my computer (old temp files maybe, and, my database)

Now, no probem to use the last dev version with a french Windows 10 64bits
Set GUI Zoom WORK
Changing Theme WORK

All is good !!! :)

**Comment by Asnivor** [comment]
@Crisis2032 thats great news! thanks for the feedback :)
