### ISSUE TITLE
new table is good... some suggestions (or future enhancements?)

### ISSUE THREAD

**Issue by retro-wertz** [Asnivor/MedLaunch#39]
good update, unscrapped data is faster now. i dont need to unnecessarily wait for it to load if i accidentally click on it. some few suggestions though.

-gamesdb seems to be really slow(not to mention i have a slow internet) and srapping just my 2000+ library of nes games took me almost an hour (including scrapping for already scrapped data from before the update) that i had to cancel it. its just slow even just getting the basic info of the game(like for the necessary entry in the table). have you considered using DAT's that are available like from TOSEC, ReDump, NoIntro etc to fill-in the basic info like game name, publisher, year etc? this way its a local copy and it has even crc/sha1 values for each rom to exactly match them to the rom you have and possibly give it proper name than the filename you have.

-scrapping an already scrapped library, does not fill in the table(only the newly added ones). the problem is you need to individually reidentify and rescrapped those games again one-by-one. i dont see how i can batch rescrap those again, and since db does not have friendly names nor organized by folders, i dont know which to delete so i can use the batch rescrapping again for specific platform or library

-allow custom resolution selection in fullscreen resolution of config

-(this needs checking-i havent looked yet)but is there no overscan option with pce_fast in mednafen core? 

-let UI remember sort method choosen- i want games sorted by game title, but it seems to sort by ID everytime i visit the library.

-allow closing the right panel windows to see more of the table.(found how to remove this :D)

(probably for advance/developer builds or options?)
-allow a link somewhere in UI to be able to load the stdout.txt and possibly stderr.txt generated by mednafen

-allow to see and modify(or allow overrides) command-line before launch? probably put it beside stdout/stderr button?

(im just quickly glancing at new update now. pls disregard suggestion above if already implemented.)

**Comment by Asnivor** [comment]
Great feedback, thanks. If you dont mind i'm going to move these all in to separate issues (where necessary) so it's easier to work with.

> -gamesdb seems to be really slow(not to mention i have a slow internet) and srapping just my 2000+ library of nes games took me almost an hour (including scrapping for already scrapped data from before the update) that i had to cancel it. its just slow even just getting the basic info of the game(like for the necessary entry in the table). have you considered using DAT's that are available like from TOSEC, ReDump, NoIntro etc to fill-in the basic info like game name, publisher, year etc? this way its a local copy and it has even crc/sha1 values for each rom to exactly match them to the rom you have and possibly give it proper name than the filename you have.

I'll hopefully look into the feasibility of this at some point.

https://github.com/Asnivor/MedLaunch/issues/40

> -scrapping an already scrapped library, does not fill in the table(only the newly added ones). the problem is you need to individually reidentify and rescrapped those games again one-by-one. i dont see how i can batch rescrap those again, and since db does not have friendly names nor organized by folders, i dont know which to delete so i can use the batch rescrapping again for specific platform or library

https://github.com/Asnivor/MedLaunch/issues/41

> -allow custom resolution selection in fullscreen resolution of config

https://github.com/Asnivor/MedLaunch/issues/42

> -(this needs checking-i havent looked yet)but is there no overscan option with pce_fast in mednafen core?

This is unfortunately a limitation of pce_fast within Mednafen:
http://mednafen.fobby.net/documentation/pce_fast.html


> -let UI remember sort method choosen- i want games sorted by game title, but it seems to sort by ID everytime i visit the library.

Yes, I'll work on this.

https://github.com/Asnivor/MedLaunch/issues/43

> -allow closing the right panel windows to see more of the table.(found how to remove this :D)

:)

> (probably for advance/developer builds or options?)
> -allow a link somewhere in UI to be able to load the stdout.txt and possibly stderr.txt generated by mednafen

This is something that is my list of things to do (although havent gotten around to formalising it on github)

https://github.com/Asnivor/MedLaunch/issues/44

> -allow to see and modify(or allow overrides) command-line before launch? probably put it beside stdout/stderr button?

That will require some thinking about.

https://github.com/Asnivor/MedLaunch/issues/45

Thanks :)
