### ISSUE TITLE
Unable to change value for "Joystick Axis Threshold". Always reverts back to 75.

### ISSUE THREAD

**Issue by acepow3r** [Asnivor/MedLaunch#53]
Confirmed for the cores of PC Engine, PC-FX, Atari Lynx, Nintendo Virtual Boy, probably all others. Whenever I change the value and despite I do save changes, the value reverts to original 75.
Seems the problem is that MedLaunch, stores the value at the config file as an alphanumeric string?

**Comment by retro-wertz** [comment]
@Asnivor 
confirmed

**Comment by Asnivor** [comment]
Will be in next release
