### ISSUE TITLE
[Enhancement/Suggestion]Allow manual input for real-type values

### ISSUE THREAD

**Issue by retro-wertz** [Asnivor/MedLaunch#55]
***Expected behavior** - allow to manually input whole and decimal values to options that supports them (e.g.  mouse_sensitivity,  goat-related settings)

***Actual behavior** - e.g.  want to input 1.25, when pressing "."(dot), it will not accept or no input happens.  it does accept decimal only values (e.g. .25, .5)

its faster and more accurate to type in numbers to the decimal value than when using the sliders.

**Comment by Asnivor** [comment]
Looks like a drawback of the default textbox implementation in WPF. I should be able to work around it with the solution here:   http://stackoverflow.com/questions/16914224/wpf-textbox-to-enter-decimal-values
