### ISSUE TITLE
Archive support

### ISSUE THREAD

**Issue by trumpetlicks** [Asnivor/MedLaunch#63]
This looks to already be an AMAZING frontend for Mednafen.  I do wonder if you have any plans to add archive scanning (.zip, .rar, .7z, etc...) and ROM support???

**Comment by Asnivor** [comment]
Hi.

Zip archive support is already there (as long as its one rom per archive and the rom has an extension that is 'allowed' for the particular system you are scanning for).

I just finished 7z support in the same fashion - this has been committed to the master branch and will be in the next release.

RAR support is possible - but I will only bother to implement if anyone actually uses it.

**Comment by trumpetlicks** [comment]
Somehow, medgui reborn is scanning all my files (regardless of 7z or zip, and regardless of multiple per file) but this software is not!  

Interesting!

Thanks much

**Comment by Asnivor** [comment]
Yeah, I think Speedvicio has built support into MedGUI reborn for multiple roms in one archive. It's not something I am currently planning on doing.

If MedLaunch is not picking up a single rom inside an archive it is likely the rom inside does not have a file extension that I have allowed for that system. The class showing the list of allowed extensions is here:

https://github.com/Asnivor/MedLaunch/blob/master/MedLaunch/Models/GSystem.cs#L157

It could be I am missing a type of rom that mednafen actually supports. If you think I am then please let me know.

**Comment by Asnivor** [comment]
Anyway, the new release should be out early next week that contains the 7zip support.

Thanks!

**Comment by trumpetlicks** [comment]
I think that is the biggest necessity :-)  Great work, I know (as I am a developer also), we get used to hearing what is wrong, but from my perspective the only reason I will contact someone with a bug, is because their product is amazing.  Just wanted you and your team to know.
Looks GREAT.
 

    On Friday, February 10, 2017 3:37 PM, Asnivor <notifications@github.com> wrote:
 

 Anyway, the new release should be out early next week that contains the 7zip support.Thanks!—

**Comment by Asnivor** [comment]
Released: https://github.com/Asnivor/MedLaunch/releases/tag/0.4.2.0
