### ISSUE TITLE
Customize List Columns

### ISSUE THREAD

**Issue by trumpetlicks** [Asnivor/MedLaunch#65]
It would be great if the game listings could be customized such that one could have as many or as few of the provided column categories as you like.  Currently it always shows all columns.

Further, it would be great if this was customizable per system / category.  As an example, when I am viewing my favorites, I would still like to see the system column, but when I am looking at a single system, that column is not necessary!

**Comment by Asnivor** [comment]
That *should* be do-able. I have looked at this before and ran into some issue. I'll take a look over the coming weeks and see if I can figure out the best way to implement this.

**Comment by Asnivor** [comment]
@trumpetlicks OK I am getting there.

![image](https://cloud.githubusercontent.com/assets/7911038/22939340/4077eace-f2d6-11e6-8e7d-2aa2debf841e.png)

Not really sure if there is a better/prettier way to lay it out, but it should at least be functional once i have the logic coded.

**Comment by trumpetlicks** [comment]
Interesting,I like that for editing them all at once.  I originally was thing about a single row of your interface in each one of your individual system configuration windows.
Ryan 

    On Tuesday, February 14, 2017 11:56 AM, Asnivor <notifications@github.com> wrote:
 

 @trumpetlicks OK I am getting there.Not really sure if there is a better/prettier way to lay it out, but it should at least be functional once i have the logic coded.—
