### ISSUE TITLE
Crash on Windows 10 

### ISSUE THREAD

**Issue by Sakimotor** [Asnivor/MedLaunch#68]
I set up my mednafen directory but now when I try to launch the program it just crashes.

OS : Windows 10 64-bit Professional 

I have Microsoft NET 4.5.2 (or above)

**Comment by retro-wertz** [comment]
im on windows 10, does not seem to crash here.

**Comment by Asnivor** [comment]
@Sakimotor Are you saying that it crashes now as soon as you start MedLaunch? Or when you try to launch a mednafen game through MedLaunch?

In your mednafen folder, there should be an Exceptions.log file. Are you able to post the contents of that file here?

**Comment by Sakimotor** [comment]
As soon at it starts, and there goes the pastebin (the log is full of french words, sorry) : http://pastebin.com/2UYuZ9jq

**Comment by Asnivor** [comment]
Thanks for the pastebin. I can see what the issue is and will try to fix today.
