### ISSUE TITLE
Allow scraping of "Favorites" List

### ISSUE THREAD

**Issue by trumpetlicks** [Asnivor/MedLaunch#75]
I have had issues with multiple frontends dying in the middle of a scrape.  I have heard that the issue is with the online DB, not the programs using it.  If your game list is large, the online DB doesn't like it!

That being said, it would be nice to be able to create my favorites list from the differing systems, and simply scrape only my favorites list to limit the amount of access to the online DB!!!

Hope this is thought a useful update :-)

**Comment by Asnivor** [comment]
That's a great suggestion (and easy to implement). Thanks.

**Comment by trumpetlicks** [comment]
Another note on this line, would be a multi-select based scraping.  Right now your interface only allows selection of a single item in a list.  If you were to enable multi-select (and disable starting of a ROM when there are multiple items selected), you could allow users to lets say select 10 items at a time, right click on the multi-selection, and scrape only the items within their multi-selection.  This way if you ultimately did want to scrap an entire collection, you could do so fast than 1 at a time, but without the problems inherent to trying to scrape the entire list at once.
