### ISSUE TITLE
Multiple Files within single archives

### ISSUE THREAD

**Issue by trumpetlicks** [Asnivor/MedLaunch#76]
I know that this is an issue you may not want to take on, but it seems as if so many of the ROM archives available today contain multiple ROM files within singular archives, and that there may a lot of value in adding this capability to this system.

Along with this, adding the ability to show parent / child relationship (with abilities to show all children, hide all children, of expand contract each parent individually)

**Comment by Asnivor** [comment]
So how does this usually work? An archive for one game that has multiple revision/regions of the game inside?

**Comment by trumpetlicks** [comment]
Yes plus sometimes hack / modified versions, or simply updated revisions!  The point is that lately this seems to be how many rom sets aired packaged.

Thanks for looking into :-)

**Comment by retro-wertz** [comment]
they are packed that way for download purposes(reduce file size, more
compression etc), not for playing. need to extract the rom you need to play

**Comment by trumpetlicks** [comment]
@retro-wertz - I think just like myself, people have large rom collections and like to keep them archived for space reasons.  I think this is why so many frontends, as well as the emulators themselves are moving toward (as well as already being there) directly opening the archive files.  MAME is this way, Mednafen (which is what this frontend supports) opens archives (for ROM files only at this point), etc...

**Comment by retro-wertz** [comment]
there is no problem opening loading roms from archieves, loading specific
roms in that archive is. mame/fba roms are handled differently compared to
normal roms/alt-roms/hacks and etc

**Comment by trumpetlicks** [comment]
Yes I understand that mame handles them differently, and perhaps that was a poor example for me to use LOL.  There are however still many frontends as well as many direct emulators that are indeed handling the opening of specific ROMs (game revisions) within a multi-ROM archive.

Anyway, I personally think this is the best frontend for Mednafen I have seen yet.  If it could indeed be figured out, I do think this would be a great addition to this frontend :-)

**Comment by Asnivor** [comment]
This will be in the next release, with the following restrictions:

- Archives must be either .zip or .7z
- Folders within the archive will be ignored
- ROMs inside the archive that are themselves compressed into another archive will be ignored
- All ROMs inside an archive *must* be for the same game system
