### ISSUE TITLE
Limit displayed ROMs in list to selected countries

### ISSUE THREAD

**Issue by trumpetlicks** [Asnivor/MedLaunch#77]
Sometimes, in a large list, I might be looking for a ROM, but want only to see the US roms, and not the JP or EU roms.  It would be nice to be able to view ROMs only if they are within the set of selected countries.

**Comment by Asnivor** [comment]
Interesting, ill think about this. The DAT lookup on each rom is not perfect at the moment. Ithe DATappears to be missing some country codes, even though the rom name from nointro contains it. I'll work some more on the dat creation routine soon.

**Comment by trumpetlicks** [comment]
Yeah, I was wondering if it was something like that :-)
