### ISSUE TITLE
[Feature Request]Separate ROM lists for different system(NES-FDS, GB-GBC) that use same emulator

### ISSUE THREAD

**Issue by retro-wertz** [Asnivor/MedLaunch#83]
Feature request to have separate ROM list for different systems even if used the same emulator core. For example:
NES,Famicon(and Dendy ROMS) use cartridges which runs in nes_emulator in one list, FDS which runs nes_emulator but the media is different(disks-hench my term different system).
Gameboy and Gameboy Color too are different systems - because they are of different generations

Please do not think this as a proposal to separate by region though-thats a different thing :D

collectors usually separate NES roms from FDS(at least I do), so its quite a neat feature to have it on launcher with its own fds directory and fds listings. this can share the config since both use the same emulator though.

thanks.

**Comment by Asnivor** [comment]
Hmmm, I'll think about it :)

**Comment by trumpetlicks** [comment]
On that note, most users separate their Gameboy and Gameboy Color collections!!!

**Comment by Asnivor** [comment]
Ok, both convincing arguments. I guess I would have to do the same with wswan and wswan color as well.  This will be one of those things I look at once controller configuration has been nailed (that is taking up most of my limited brain power at the moment).

**Comment by Asnivor** [comment]
I've decided to leave the system filters as they are. Aside from the PC-Engine (CD) entry, these exactly mirror the various Mednafen cores (and this after all is a mednafen front-end).

However, with the introduction of multi-tier sorting in the games library, MedLaunch will now (at next release) detect different variations of systems (GB/GBC, NGP/NGC, WSWAN/WSWAN-COLOR, NES/FDS) at scan-time and display this system in the 'SYSTEM' column in the games library. You can then sort how you want (i.e. sort by system, then shift-click to sort by game name etc.).

Hopefully this is a happy compromise. 

![image](https://user-images.githubusercontent.com/7911038/27546840-df6b31e6-5a8b-11e7-9ac3-1ca6d47b6af3.png)

![image](https://user-images.githubusercontent.com/7911038/27546864-f0c68594-5a8b-11e7-80b0-f6c56d8f1776.png)

![image](https://user-images.githubusercontent.com/7911038/27546878-00683e0c-5a8c-11e7-9f21-f76266ee656a.png)

![image](https://user-images.githubusercontent.com/7911038/27546906-17e75810-5a8c-11e7-9b30-2c289f97fc0d.png)
