### ISSUE TITLE
Sound Device Option is always default

### ISSUE THREAD

**Issue by ffmasterfoobar** [Asnivor/MedLaunch#86]

**Comment by Asnivor** [comment]
In the launcher itself (after saving)? Or in mednafen once you have launched a game?

**Comment by ffmasterfoobar** [comment]
Yes. While there is an  option for sound driver, for sound device in medlaunch there is not. It always saves to default in it even if I change it through mednafen-09x.cfg & the corresponding game system cfg file before.  Mednafen by itself is fine.  The only option in medlaunch currently is to edit the launch string every time.

**Comment by Asnivor** [comment]
Ahh ok, I understand now. I am actually missing the option to set the 'sound.device' string. I'll get this fixed soon (likely by just a textbox for you to type in to start with).

I might eventually be able to code something that enumerates local sound devices, but this wont be high on the list of priorities.
