### ISSUE TITLE
Populate PSX library data on scan using serial number

### ISSUE THREAD

**Issue by Asnivor** [Asnivor/MedLaunch#91]
md5 hash matching appears to be unreliable

**Comment by retro-wertz** [comment]
serial labels should be available in bin file, even on pbp

**Comment by Asnivor** [comment]
Yeah, I already am pulling the serial number out of the image (in order to do an SBI file check). I kinda want to match this serial against a list of known PSX games in order to populate various info in the games library at scan time.
