### ISSUE TITLE
Game Stats Game Name field too smalle for long names

### ISSUE THREAD

**Issue by trumpetlicks** [Asnivor/MedLaunch#95]
Now that the multi-files per zip file is working, the "Game:" field inside of the "Game Stats" sub-window is not large enough to show entire names many times.

This could be fixed by having that field be 2 lines or more high, or by allowing the entire right panel to be re-sized.

Great Job by the way :-)

**Comment by Asnivor** [comment]
Allowing the right sidebar to be resized is a nice idea, but from a technical implementation perspective I don't think I can easily (and quickly) achieve this.

Having that field be 2 or more lines higher (and having the text auto-wrap) would work most of the time, except if game file names do not have any spaces in them (this kind of edge case is bound to present itself at some point).

For now i've enclosed the whole 'game stats' grid in a horizontal scrollviewer (that remains hidden unless any of the text overflows the boundaries). Hopefully this is a happy compromise.
