### ISSUE TITLE
[Suggestion] Allow also adding/scanning disks in current selected folder

### ISSUE THREAD

**Issue by retro-wertz** [Asnivor/MedLaunch#96]
not entirely necessary and not sure if somebody else is doing it, but most of the time i reconvert stuff into single cue/bin formats and put them in one folder without using subfolders for each title.

**Comment by Asnivor** [comment]
So one folder with multiple bin/cue files (with potentially multiple discs per game)?

**Comment by Asnivor** [comment]
After consideration, this is not something I will be implementing right now (but thats not to say it wont happen at some point in the future).

Until then, users can manually add disc-based games if they dont want to separate them by individual folder.

**Comment by Asnivor** [comment]
Looking at this again in #180
