### ISSUE TITLE
[Bug] Medlauch stopped working (while scraping a single title), then quits out

### ISSUE THREAD

**Issue by trumpetlicks** [Asnivor/MedLaunch#97]
It happened for me when I was trying to scrape (single game) of Actraiser 2 for Super Nintendo.  Whether I chose the 1st or 2nd option that comes up in the list, it does the same thing and quits out.

**Comment by retro-wertz** [comment]
this happened to me too, though i cannot recreate it that time.

**Comment by Asnivor** [comment]
Can you post your Exceptions.log file (from the medlaunch directory) here please?

**Comment by Asnivor** [comment]
@trumpetlicks If you can dig the Exceptions.log file out next time you have a chance that would be great. Should tell me exactly what the problem is (and I cant replicate it myself).

Thanks.

**Comment by Asnivor** [comment]
I think this was due to intermittent lookups to thegamesdb not returning an actual game (even though one is present). This should be mitigated now. Will close on next release and reopen if problem still persists.
